version: "3"
services:
  mongo:
    image: mongo:3.4
    command: --smallfiles
    volumes:
      - data:/data/db
    expose:
      - 27017
  app:
    build: .
    expose:
      - 3000
    depends_on:
      - mongo
  cli:
    build: .
    command: sh
    stdin_open: true
    tty: true
    depends_on:
      - app

volumes:
  data:
