version: "3"
services:
  mongo:
    image: mongo:3.4
    command: --config /etc/mongod.conf
    volumes:
      - data:/data/db
      - ./mongod.yaml:/etc/mongod.conf
    expose:
      - 27017
  app:
    build: .
    expose:
      - 3000
    depends_on:
      - mongo
    labels:
      # NOTE: access app instances from localhost and cli container
      - "traefik.frontend.rule=Host:localhost,balancer"
  cli:
    build: .
    command: sh
    stdin_open: true
    tty: true
    depends_on:
      - app
  balancer:
    image: traefik
    command: --docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app

volumes:
  data:
