version: "3"
services:
  mongo01:
    image: mongo:3.4
    command: --config /etc/mongod.conf
    volumes:
      - data01:/data/db
      - ./mongod.yaml:/etc/mongod.conf
    expose:
      - 27017
  mongo02:
    image: mongo:3.4
    command: --config /etc/mongod.conf
    volumes:
      - data02:/data/db
      - ./mongod.yaml:/etc/mongod.conf
    expose:
      - 27017
  mongo03:
    image: mongo:3.4
    command: --config /etc/mongod.conf
    volumes:
      - data03:/data/db
      - ./mongod.yaml:/etc/mongod.conf
    expose:
      - 27017
  app:
    build: .
    expose:
      - 3000
    env_file:
      - ./soldcars.env
    depends_on:
      - cli
    labels:
      # NOTE: access app instances from localhost and cli container
      - "traefik.frontend.rule=Host:localhost,balancer"
  cli:
    build: .
    command: sh
    stdin_open: true
    tty: true
    env_file:
      - ./soldcars.env
    depends_on:
      - mongo01
      - mongo02
      - mongo03
  balancer:
    image: traefik
    command: --docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app

volumes:
  data01:
  data02:
  data03:
